// Human-readable learning layer.
// Detection is evidence-based; these explanations describe what the technology is,
// why developers use it, and what a signal can (and cannot) prove.
const TECH_DETAILS = {
  "WordPress": ["CMS", "A PHP-based publishing platform. It manages content, themes and plugins; seeing wp-content/wp-includes is a strong fingerprint."],
  "WooCommerce": ["Commerce", "An ecommerce layer for WordPress that adds products, carts, orders and checkout."],
  "Shopify": ["Commerce", "A hosted ecommerce platform. Shopify assets, globals and cookies can reveal the storefront runtime."],
  "Wix": ["CMS", "A hosted site-building platform that supplies the page runtime, content system and deployment infrastructure."],
  "Webflow": ["CMS", "A visual website platform that can generate the site's HTML/CSS and runtime assets without a traditional app server."],
  "React": ["UI", "A component-based JavaScript UI library. Detection means React-related runtime markers or assets were exposed to the page."],
  "Next.js": ["Full-stack UI", "A React framework that can handle routing, server rendering, static generation and API/server functions."],
  "Vue.js": ["UI", "A progressive JavaScript framework used to build reactive component-based interfaces."],
  "Nuxt.js": ["Full-stack UI", "A Vue framework that adds routing, server rendering, data fetching and deployment conventions."],
  "Angular": ["UI", "A full-featured TypeScript framework with components, dependency injection, routing and tooling."],
  "Svelte": ["UI", "A compiler-based UI framework that turns components into efficient JavaScript rather than shipping a large runtime."],
  "SvelteKit": ["Full-stack UI", "Svelte's application framework for routing, rendering modes, data loading and server endpoints."],
  "jQuery": ["Library", "A mature JavaScript utility library historically used for DOM manipulation, events and AJAX."],
  "Three.js": ["Graphics", "A JavaScript 3D rendering library commonly backed by WebGL/WebGPU."],
  "GSAP": ["Animation", "A high-performance JavaScript animation engine used for timelines, transforms and interaction."],
  "Axios": ["Networking", "A promise-based HTTP client commonly used to call APIs from browser JavaScript."],
  "Socket.IO": ["Realtime", "A realtime communication library that commonly uses WebSocket with fallbacks and its own protocol."],
  "Bootstrap": ["UI", "A component and utility CSS framework with a large convention-based class system."],
  "Tailwind CSS": ["UI", "A utility-first CSS framework where visual styling is composed from small classes."],
  "Material UI": ["UI", "A React component system implementing Material Design patterns with themeable components."],
  "Radix UI": ["UI", "An accessible, unstyled React primitive library used as the behavioral foundation for custom design systems."],
  "shadcn/ui": ["UI", "A copy-into-your-code component approach commonly built on Radix primitives and Tailwind CSS."],
  "Google Analytics (GA4)": ["Analytics", "Google's event-oriented analytics platform for measuring acquisition, engagement and conversions."],
  "Google Tag Manager": ["Analytics", "A tag orchestration layer that lets teams deploy marketing and measurement scripts through a managed container."],
  "Segment": ["Analytics", "A customer data platform that collects events and routes them to analytics, marketing and warehouse destinations."],
  "Hotjar": ["Analytics", "Behavior analytics tooling for heatmaps, recordings, feedback and qualitative UX research."],
  "Microsoft Clarity": ["Analytics", "Free behavior analytics focused on session recordings, heatmaps and UX diagnostics."],
  "Sentry": ["Observability", "Error and performance monitoring that captures frontend exceptions, traces and related diagnostics."],
  "Datadog RUM": ["Observability", "Real-user monitoring that measures browser sessions, performance and frontend errors."],
  "New Relic Browser": ["Observability", "Browser monitoring for real-user performance, errors and page-load behavior."],
  "Cloudflare": ["Infrastructure", "A globally distributed edge platform commonly used for DNS, CDN, caching, TLS and security."],
  "Cloudflare Web Analytics": ["Observability", "A privacy-oriented web analytics product delivered from Cloudflare's edge."],
  "Vercel": ["Infrastructure", "A deployment platform strongly associated with frontend/serverless applications and edge delivery."],
  "Amazon CloudFront": ["Infrastructure", "AWS's content delivery network for serving web assets and applications from edge locations."],
  "Google Cloud": ["Infrastructure", "Google's cloud platform; browser-visible domains and headers can expose services without revealing the entire backend."],
  "Amazon Web Services": ["Infrastructure", "AWS provides compute, storage, networking and managed services; client-side fingerprints usually identify a service rather than the whole architecture."],
  "Nginx": ["Web server", "A high-performance HTTP server and reverse proxy commonly placed in front of application servers."],
  "Apache": ["Web server", "A widely used HTTP server often acting as the origin or reverse proxy for web applications."],
  "Express": ["Backend", "A minimalist Node.js web framework used for HTTP APIs, middleware and server-side routing."],
  "Django": ["Backend", "A Python web framework emphasizing batteries-included development, routing, models, templates and security."],
  "Laravel": ["Backend", "A PHP framework with routing, middleware, ORM, queues and application tooling."],
  "GraphQL": ["API", "A query language and API runtime where clients request structured fields instead of fixed REST responses."],
  "Apollo GraphQL": ["API", "A GraphQL client/server ecosystem with caching, schema tooling and application integration."],
  "Firebase": ["Backend service", "Google's managed app platform offering services such as authentication, databases, hosting, analytics and messaging."],
  "Supabase": ["Backend service", "A developer platform built around Postgres with database APIs, authentication, storage and realtime features."],
  "Stripe": ["Payments", "A payments platform. Browser scripts and checkout domains can reveal that Stripe is involved, but not the merchant's full payment architecture."],
  "OneTrust": ["Privacy", "Consent management tooling used to control cookies and tracking choices."],
  "Cookiebot": ["Privacy", "A consent management platform for cookie scanning and privacy preference collection."],
  "Auth0": ["Authentication", "An identity platform handling login, tokens, social identity providers and user management."],
  "Clerk": ["Authentication", "An authentication/user-management platform providing prebuilt sign-in UI and session infrastructure."],
  "Firebase Authentication": ["Authentication", "Firebase's managed identity service supporting email, social providers and application sessions."],
  "AWS Cognito": ["Authentication", "AWS identity service for user pools, federated identity and application authentication."],
  "Open Graph Protocol": ["Metadata", "Social sharing metadata that controls how a page can appear when its URL is shared."],
  "Schema.org / JSON-LD": ["SEO", "Structured metadata that helps search engines understand entities such as products, articles and organizations."],
  "Progressive Web App (PWA)": ["Web platform", "A web app using capabilities such as a manifest and service worker to behave more like an installable app."],
  "HTTP/3 (QUIC)": ["Performance", "The HTTP version built over QUIC/UDP, designed to reduce connection latency and improve resilience."],
  "Brotli Compression": ["Performance", "A compression format that can reduce transferred response size, especially for text assets."],
  "Lazy Loading (native)": ["Performance", "Browser-native deferred loading that avoids fetching certain resources until they are closer to use."],
  "Resource Hints (preconnect/prefetch)": ["Performance", "HTML hints that let browsers establish connections or fetch likely-needed resources earlier."],
  "Priority Hints (fetchpriority)": ["Performance", "A browser hint for expressing relative importance of individual resource fetches."],
  "Web Components": ["Web platform", "Browser-native custom elements, shadow DOM and related APIs for reusable components."],
  "Dark Mode Support": ["Web platform", "CSS/media-query behavior allowing a site to adapt its appearance to the user's color-scheme preference."],
  "Google Maps": ["Maps", "Google's mapping APIs and embeds for maps, places and geospatial interaction."],
  "Mapbox": ["Maps", "A mapping platform for interactive maps, tiles, geocoding and location experiences."],
  "Leaflet": ["Maps", "A lightweight open-source JavaScript library for interactive maps."],
  "YouTube": ["Video", "Google's video platform, commonly embedded through iframes or player integrations."],
  "Vimeo": ["Video", "A video hosting and playback platform commonly embedded into sites."],
  "YouTube": ["Video", "Google's video platform, commonly embedded through iframes or player integrations."],
  "Sign in with Apple": ["Authentication", "Apple's OAuth/OpenID-style sign-in flow for letting users authenticate with Apple accounts."],
  "Google Sign-In": ["Authentication", "Google identity tooling for account sign-in and identity tokens."],
  "Microsoft Identity (MSAL)": ["Authentication", "Microsoft Authentication Library used by browser apps to obtain identity and access tokens."],
};

const CATEGORY_LEARN = {
  "CMS":"Content publishing layer — ask what owns the content, templates and editorial workflow.",
  "Ecommerce":"Commerce layer — look for product APIs, cart state, checkout and payment integrations.",
  "JS Frameworks":"Application UI layer — inspect rendering, routing, hydration and client bundles.",
  "JS Libraries":"Supporting JavaScript capabilities — identify what problem each library solves.",
  "UI Frameworks":"Design-system layer — inspect utility classes, components, tokens and accessibility patterns.",
  "Analytics":"Measurement layer — identify events, cookies, consent behavior and third-party destinations.",
  "Tag Managers":"Script orchestration — a site may load many other technologies indirectly through one tag container.",
  "CDN":"Edge delivery — assets can be cached close to users before reaching the origin.",
  "PaaS":"Deployment layer — a fingerprint can hint at hosting, but rarely proves the entire infrastructure.",
  "Web Servers":"HTTP origin/proxy layer — often sits between the browser and the actual application.",
  "Web Frameworks":"Backend application layer — routes, middleware, templates, sessions and APIs.",
  "Security":"Traffic protection — CDN/WAF/bot layers can hide the real origin stack.",
  "Payment":"Payment infrastructure — browser fingerprints show integrations, not necessarily where funds settle.",
  "Authentication":"Identity layer — learn how sessions, tokens and providers connect to the application.",
  "Performance":"Delivery strategy — inspect compression, caching, connection setup and loading priorities.",
  "RUM":"Observability — real user telemetry reveals performance and errors after deployment.",
  "Miscellaneous":"Web platform clues — small details can reveal architecture, SEO strategy and browser capabilities."
};

function getTechExplanation(tech) {
  const d = TECH_DETAILS[tech.name];
  if (d) return {role:d[0], text:d[1]};
  const role = CATEGORY_LEARN[tech.category] ? tech.category : "Web technology";
  return {role, text:`${tech.name} was detected through browser-visible signals. The signal identifies a likely technology or capability, but does not by itself prove every part of the site's architecture.`};
}
